-- QUERY 1: What is the frequency of purchases by Country?
SELECT 
    Country_x, 
    count(DISTINCT Order_Number) AS Frequency_of_Purchases
FROM 
    dataspark.sales_customer_product_store
GROUP BY 
    Country_x;
    
-- QUERY 2: What is the average Sales of individual brands?
SELECT
    Brand,
    round(Avg(Quantity * Unit_Price_USD)) AS Average_Sales
FROM
    dataspark.sales_customer_product_store
GROUP BY
    Brand
ORDER BY
    Average_Sales DESC;

-- QUERY 3: How can we segment customers based on their purchase frequency and the total quantity of items they purchased?
SELECT 
    CustomerKey, 
    COUNT(Order_Number) AS Number_Of_Purchases, 
    SUM(Quantity) AS Total_Quantity_Purchased,
    round(AVG(Quantity)) AS Average_Quantity_Per_Purchase
FROM 
    dataspark.sales_customer_product_store
GROUP BY 
    CustomerKey
ORDER BY 
    Number_Of_Purchases DESC;
 -- Query 4: what is the total Quantity Sold And total revenue generated by Top Performing Products ?
SELECT 
    ProductKey, 
    Product_Name, 
    SUM(Quantity) AS Total_Quantity_Sold,
    round(sum(Quantity * Unit_Price_USD)) AS TotalRevenueGenerated
FROM 
    dataspark.sales_customer_product_store
GROUP BY 
    ProductKey, Product_Name
ORDER BY 
    Total_Quantity_Sold DESC
LIMIT 20;

-- QUERY 5:  What are the most popular and least popular product based on quantity sold?
WITH Popularity AS (
    SELECT 
        Product_Name, 
        SUM(Quantity) AS Total_Quantity_Sold
    FROM 
        dataspark.sales_customer_product_store
    GROUP BY 
        Product_Name
)
SELECT 
    (SELECT Product_Name FROM Popularity ORDER BY Total_Quantity_Sold DESC LIMIT 1) AS Most_Popular_Product,
    (SELECT Product_Name FROM Popularity ORDER BY Total_Quantity_Sold ASC LIMIT 1) AS Least_Popular_Product;
    
-- QUERY 6: How does store performance vary based on sales, size (square meters), and the date of opening?
SELECT 
    StoreKey,
    min(Open_Date) AS Date_Of_Open,
    SUM(Quantity) AS Total_Quantity_Sold,
    round(SUM(Quantity * Unit_Price_USD)) AS Total_Sales_Revenue,
    AVG(Square_Meters) AS Average_Store_Size
FROM 
    dataspark.sales_customer_product_store
GROUP BY 
    StoreKey
ORDER BY 
    Total_Sales_Revenue DESC
LIMIT 20;
 
 -- QUERY 7: How has the store performance varied in terms of total sales over time?
 SELECT 
    StoreKey, 
    YEAR(Order_Date) AS Year, 
    MONTH(Order_Date) AS Month, 
    round(SUM(Quantity * Unit_Price_USD)) AS Monthly_Sales
FROM 
    dataspark.sales_customer_product_store
GROUP BY 
    StoreKey, 
    YEAR(Order_Date), 
    MONTH(Order_Date)
ORDER BY 
    StoreKey, 
    Year, 
    Month;

-- QUERY 8: What is the profit margin of Products
SELECT 
    Product_Name, 
    round(SUM((Unit_Price_USD - Unit_Cost_USD) * Quantity)) AS Total_Profit,
    round(SUM(Quantity * Unit_Price_USD)) AS Total_Revenue,
    (SUM(( Unit_Price_USD - Unit_Cost_USD ) * Quantity) / SUM(Quantity * Unit_Price_USD)) * 100 AS Profit_Margin_Percentage
FROM 
    dataspark.sales_customer_product_store
GROUP BY 
    Product_Name
ORDER BY 
    Profit_Margin_Percentage ;
    
-- QUERY 9: What is the preferred brand of customers in different age groups (20-30, 30-40, 40-50, 50-60, 60+) based on total sales?
WITH CustomerAgeGroups AS (
    SELECT
        CASE
            WHEN YEAR(CURDATE()) - YEAR(CAST(Birthday AS DATE)) BETWEEN 20 AND 29 THEN '20-30'
            WHEN YEAR(CURDATE()) - YEAR(CAST(Birthday AS DATE)) BETWEEN 30 AND 39 THEN '30-40'
            WHEN YEAR(CURDATE()) - YEAR(CAST(Birthday AS DATE)) BETWEEN 40 AND 49 THEN '40-50'
            WHEN YEAR(CURDATE()) - YEAR(CAST(Birthday AS DATE)) BETWEEN 50 AND 59 THEN '50-60'
            WHEN YEAR(CURDATE()) - YEAR(CAST(Birthday AS DATE)) >= 60 THEN '60+'
            ELSE 'Under 20'  -- Optional for handling ages under 20
        END AS AgeGroup,
        Brand,
        round(SUM(Quantity * Unit_Price_USD)) AS TotalSales
    FROM
        dataspark.sales_customer_product_store
    GROUP BY
        AgeGroup,
        Brand        )
SELECT 
    AgeGroup,
    Brand,
    TotalSales
FROM 
    CustomerAgeGroups
ORDER BY 
    AgeGroup;

-- QUERY 10: What is the total profit generated by each currency from product sales?
SELECT 
    Currency_Code,
    round(SUM((Unit_Price_USD - Unit_Cost_USD) * Quantity)) AS Total_Profit
FROM 
    dataspark.sales_customer_product_store
GROUP BY 
    Currency_Code
ORDER BY 
    Total_Profit DESC;
